<a href="https://colab.research.google.com/github/mahalakshmimarri06-gif/IncodeVision-Tasks/blob/main/Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('crime_incidents_messy.csv')

In [7]:
df.head()

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
0,INC001115,asslt,Sou,Maplewood,GA,2830 Cedar Lane,170.284100,-77.500710,2024-04-16 08:45:03,OFF0078,...,Unknown,6223265920,Firearm,2,Open,No Arrest,NaN,NaN,True,Incident at 2830 Cedar Lane. Officer responded...
1,INC004706,burglary,southeast,Maplewood,OH,2361 Park Rd,29.422717,-77.167016,2022-01-11 22:03:29,OFF0059,...,NaN,241-973-4826,Firearm,3,NaN,NaN,2.0,44839.49,yes,Incident at 2361 Park Rd. Officer responded at...
2,INC002249,Homocide,Southwest,Lakewood,AZ,1067 Main St,39.411460,-98.615298,2022-04-14 11:39:24,OFF0088,...,Other,244-584-7696,KNIFE,1,CLOSED,warning,2.0,15963.38,YES,Incident at 1067 Main St. Officer responded at...
3,INC000021,Property Damage,Cen,Springfield,AZ,4713 Washington Ave,28.633439,-99.030051,2020-12-09 15:14:24,OFF0077,...,NaN,5021227484,hands,Low,Resolved,NaN,5.0,48680.14,False,Incident at 4713 Washington Ave. Officer respo...
4,INC000488,Domestc Violence,North,Lakewood,PA,1371 River Rd,34.217850,-121.614731,2021-07-24 20:08:13,OFF0083,...,M,9698766873,Unarmed,MEDIUM,Closed,Warning Issued,2.0,23513.01,YES,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5250 non-null   object
 1   crime_type          5250 non-null   object
 2   district            5250 non-null   object
 3   city                5250 non-null   object
 4   state               5250 non-null   object
 5   address             5250 non-null   object
 6   latitude            4992 non-null   float64
 7   longitude           4961 non-null   float64
 8   incident_datetime   4910 non-null   object
 9   officer_id          5250 non-null   object
 10  officer_first_name  5250 non-null   object
 11  officer_last_name   5250 non-null   object
 12  badge_number        4938 non-null   float64
 13  suspect_id          4440 non-null   object
 14  suspect_first_name  4440 non-null   object
 15  suspect_last_name   4440 non-null   object
 16  suspect_age         4153 non-null   float64
 17  suspect_gender      3837 non-null   object
 18  suspect_race        3649 non-null   object
 19  victim_id           4993 non-null   object
 20  victim_first_name   4993 non-null   object
 21  victim_last_name    4993 non-null   object
 22  victim_age          4688 non-null   float64
 23  victim_gender       4250 non-null   object
 24  victim_phone        4194 non-null   object
 25  weapon_used         4280 non-null   object
 26  severity            4895 non-null   object
 27  case_status         4519 non-null   object
 28  resolution          4299 non-null   object
 29  num_arrests         4917 non-null   float64
 30  property_loss_usd   4814 non-null   object
 31  reported_online     4746 non-null   object
 32  notes               4181 non-null   object
dtypes: float64(6), object(27)
memory usage: 1.3+ MB

In [9]:
df.isnull().sum()

incident_id              0
crime_type               0
district                 0
city                     0
state                    0
address                  0
latitude               258
longitude              289
incident_datetime      340
officer_id               0
officer_first_name       0
officer_last_name        0
badge_number           312
suspect_id             810
suspect_first_name     810
suspect_last_name      810
suspect_age           1097
suspect_gender        1413
suspect_race          1601
victim_id              257
victim_first_name      257
victim_last_name       257
victim_age             562
victim_gender         1000
victim_phone          1056
weapon_used            970
severity               355
case_status            731
resolution             951
num_arrests            333
property_loss_usd      436
reported_online        504
notes                 1069
dtype: int64

In [10]:
print(f"Total duplicates: {df.duplicated().sum()}")

Total duplicates: 200

In [11]:
df = df.drop_duplicates()

In [12]:
# Fill missing names with 'Unknown'
df['suspect_first_name'] = df['suspect_first_name'].fillna('Unknown')

# For IDs, you might want to use a placeholder ID like 0 or -1
df['suspect_id'] = df['suspect_id'].fillna(0)

In [13]:
df.dropna(subset=['latitude', 'longitude'], inplace=True)

In [14]:
df.dropna(subset=['incident_datetime'], inplace=True)

In [15]:
df.isnull().sum()

incident_id              0
crime_type               0
district                 0
city                     0
state                    0
address                  0
latitude                 0
longitude                0
incident_datetime        0
officer_id               0
officer_first_name       0
officer_last_name        0
badge_number           250
suspect_id               0
suspect_first_name       0
suspect_last_name      658
suspect_age            890
suspect_gender        1144
suspect_race          1290
victim_id              208
victim_first_name      208
victim_last_name       208
victim_age             455
victim_gender          808
victim_phone           838
weapon_used            776
severity               277
case_status            575
resolution             760
num_arrests            269
property_loss_usd      341
reported_online        398
notes                  860
dtype: int64

In [16]:
# Dropping columns that have too many missing values to be useful
df.drop(columns=['suspect_race', 'suspect_gender', 'victim_gender'], inplace=True)

In [17]:
df['badge_number'] = df['badge_number'].fillna(0)

In [18]:
median_suspect_age = df['suspect_age'].median()
df['suspect_age'] = df['suspect_age'].fillna(median_suspect_age)

median_victim_age = df['victim_age'].median()
df['victim_age'] = df['victim_age'].fillna(median_victim_age)

In [19]:
cols_to_fill = ['suspect_last_name', 'victim_first_name', 'victim_last_name']
df[cols_to_fill] = df[cols_to_fill].fillna('Unknown')

In [20]:
df.drop(columns=['notes', 'victim_phone'], inplace=True)

In [21]:
# Apply 'Unknown' to these categorical columns
cat_cols = ['victim_last_name', 'weapon_used', 'case_status', 'resolution']
df[cat_cols] = df[cat_cols].fillna('Unknown')

In [22]:
# Fill with median
df['property_loss_usd'] = pd.to_numeric(df['property_loss_usd'], errors='coerce')
df['property_loss_usd'] = df['property_loss_usd'].fillna(df['property_loss_usd'].median())
df['num_arrests'] = df['num_arrests'].fillna(df['num_arrests'].median())

In [23]:
df.isnull().sum()

incident_id             0
crime_type              0
district                0
city                    0
state                   0
address                 0
latitude                0
longitude               0
incident_datetime       0
officer_id              0
officer_first_name      0
officer_last_name       0
badge_number            0
suspect_id              0
suspect_first_name      0
suspect_last_name       0
suspect_age             0
victim_id             208
victim_first_name       0
victim_last_name        0
victim_age              0
weapon_used             0
severity              277
case_status             0
resolution              0
num_arrests             0
property_loss_usd       0
reported_online       398
dtype: int64

In [24]:
# Option A: Drop them
df.dropna(subset=['victim_id'], inplace=True)

In [25]:
# Using 'Unknown' to be safe
df['severity'] = df['severity'].fillna('Unknown')

In [26]:
df['reported_online'] = df['reported_online'].fillna('Unknown')

In [27]:

print(df.isnull().sum())

incident_id           0
crime_type            0
district              0
city                  0
state                 0
address               0
latitude              0
longitude             0
incident_datetime     0
officer_id            0
officer_first_name    0
officer_last_name     0
badge_number          0
suspect_id            0
suspect_first_name    0
suspect_last_name     0
suspect_age           0
victim_id             0
victim_first_name     0
victim_last_name      0
victim_age            0
weapon_used           0
severity              0
case_status           0
resolution            0
num_arrests           0
property_loss_usd     0
reported_online       0
dtype: int64

In [28]:
# Ensure datetime format
df['incident_datetime'] = pd.to_datetime(df['incident_datetime'], format='mixed')

# Extract useful features
df['hour'] = df['incident_datetime'].dt.hour
df['day_of_week'] = df['incident_datetime'].dt.dayofweek

# We can drop the original column now that we've extracted the info
df.drop(columns=['incident_datetime'], inplace=True)

In [29]:
Q1 = df['property_loss_usd'].quantile(0.25)
Q3 = df['property_loss_usd'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Cap outliers
df['property_loss_usd'] = df['property_loss_usd'].clip(lower=lower_bound, upper=upper_bound)

In [30]:
# Convert categorical strings into dummy variables (0s and 1s)
df = pd.get_dummies(df, columns=['weapon_used', 'case_status'], drop_first=True)

In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
# Select your numerical columns
numerical_cols = ['property_loss_usd', 'suspect_age', 'victim_age']
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [32]:
from sklearn.model_selection import train_test_split

# Define X (features) and y (the target column you want to predict)
# Replace 'target_column_name' with what you want to predict (e.g., 'severity')
X = df.drop(columns=['severity'])
y = df['severity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

Training set shape: (3228, 51)
Testing set shape: (808, 51)

In [33]:
# This shows you the "dtype" (data type) of every column
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4036 entries, 0 to 5248
Data columns (total 52 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   incident_id                      4036 non-null   object
 1   crime_type                       4036 non-null   object
 2   district                         4036 non-null   object
 3   city                             4036 non-null   object
 4   state                            4036 non-null   object
 5   address                          4036 non-null   object
 6   latitude                         4036 non-null   float64
 7   longitude                        4036 non-null   float64
 8   officer_id                       4036 non-null   object
 9   officer_first_name               4036 non-null   object
 10  officer_last_name                4036 non-null   object
 11  badge_number                     4036 non-null   float64
 12  suspect_id                       4036 non-null   object
 13  suspect_first_name               4036 non-null   object
 14  suspect_last_name                4036 non-null   object
 15  suspect_age                      4036 non-null   float64
 16  victim_id                        4036 non-null   object
 17  victim_first_name                4036 non-null   object
 18  victim_last_name                 4036 non-null   object
 19  victim_age                       4036 non-null   float64
 20  severity                         4036 non-null   object
 21  resolution                       4036 non-null   object
 22  num_arrests                      4036 non-null   float64
 23  property_loss_usd                4036 non-null   float64
 24  reported_online                  4036 non-null   object
 25  hour                             4036 non-null   int32
 26  day_of_week                      4036 non-null   int32
 27  weapon_used_Blunt Object         4036 non-null   bool
 28  weapon_used_Firearm              4036 non-null   bool
 29  weapon_used_Gun                  4036 non-null   bool
 30  weapon_used_Hands/Feet           4036 non-null   bool
 31  weapon_used_KNIFE                4036 non-null   bool
 32  weapon_used_Knife                4036 non-null   bool
 33  weapon_used_Pistol               4036 non-null   bool
 34  weapon_used_Rifle                4036 non-null   bool
 35  weapon_used_Unarmed              4036 non-null   bool
 36  weapon_used_Unknown              4036 non-null   bool
 37  weapon_used_blunt object         4036 non-null   bool
 38  weapon_used_firearm              4036 non-null   bool
 39  weapon_used_hands                4036 non-null   bool
 40  case_status_Closed               4036 non-null   bool
 41  case_status_Investgation         4036 non-null   bool
 42  case_status_OPEN                 4036 non-null   bool
 43  case_status_Open                 4036 non-null   bool
 44  case_status_Pending              4036 non-null   bool
 45  case_status_Pendng               4036 non-null   bool
 46  case_status_Resolved             4036 non-null   bool
 47  case_status_Under Investigation  4036 non-null   bool
 48  case_status_Unknown              4036 non-null   bool
 49  case_status_closed               4036 non-null   bool
 50  case_status_open                 4036 non-null   bool
 51  case_status_under investigation  4036 non-null   bool
dtypes: bool(25), float64(7), int32(2), object(18)
memory usage: 949.9+ KB

In [34]:
# Convert ID columns to numeric, forcing errors to NaN (which you can then fill)
df['suspect_id'] = pd.to_numeric(df['suspect_id'], errors='coerce').fillna(0).astype(int)
df['victim_id'] = pd.to_numeric(df['victim_id'], errors='coerce').fillna(0).astype(int)

# Double-check the types
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4036 entries, 0 to 5248
Data columns (total 52 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   incident_id                      4036 non-null   object
 1   crime_type                       4036 non-null   object
 2   district                         4036 non-null   object
 3   city                             4036 non-null   object
 4   state                            4036 non-null   object
 5   address                          4036 non-null   object
 6   latitude                         4036 non-null   float64
 7   longitude                        4036 non-null   float64
 8   officer_id                       4036 non-null   object
 9   officer_first_name               4036 non-null   object
 10  officer_last_name                4036 non-null   object
 11  badge_number                     4036 non-null   float64
 12  suspect_id                       4036 non-null   int64
 13  suspect_first_name               4036 non-null   object
 14  suspect_last_name                4036 non-null   object
 15  suspect_age                      4036 non-null   float64
 16  victim_id                        4036 non-null   int64
 17  victim_first_name                4036 non-null   object
 18  victim_last_name                 4036 non-null   object
 19  victim_age                       4036 non-null   float64
 20  severity                         4036 non-null   object
 21  resolution                       4036 non-null   object
 22  num_arrests                      4036 non-null   float64
 23  property_loss_usd                4036 non-null   float64
 24  reported_online                  4036 non-null   object
 25  hour                             4036 non-null   int32
 26  day_of_week                      4036 non-null   int32
 27  weapon_used_Blunt Object         4036 non-null   bool
 28  weapon_used_Firearm              4036 non-null   bool
 29  weapon_used_Gun                  4036 non-null   bool
 30  weapon_used_Hands/Feet           4036 non-null   bool
 31  weapon_used_KNIFE                4036 non-null   bool
 32  weapon_used_Knife                4036 non-null   bool
 33  weapon_used_Pistol               4036 non-null   bool
 34  weapon_used_Rifle                4036 non-null   bool
 35  weapon_used_Unarmed              4036 non-null   bool
 36  weapon_used_Unknown              4036 non-null   bool
 37  weapon_used_blunt object         4036 non-null   bool
 38  weapon_used_firearm              4036 non-null   bool
 39  weapon_used_hands                4036 non-null   bool
 40  case_status_Closed               4036 non-null   bool
 41  case_status_Investgation         4036 non-null   bool
 42  case_status_OPEN                 4036 non-null   bool
 43  case_status_Open                 4036 non-null   bool
 44  case_status_Pending              4036 non-null   bool
 45  case_status_Pendng               4036 non-null   bool
 46  case_status_Resolved             4036 non-null   bool
 47  case_status_Under Investigation  4036 non-null   bool
 48  case_status_Unknown              4036 non-null   bool
 49  case_status_closed               4036 non-null   bool
 50  case_status_open                 4036 non-null   bool
 51  case_status_under investigation  4036 non-null   bool
dtypes: bool(25), float64(7), int32(2), int64(2), object(16)
memory usage: 949.9+ KB
None

In [35]:
df['incident_id'] = pd.to_numeric(df['incident_id'], errors='coerce')
print(df['incident_id'].dtype)

float64

In [36]:
print(df['officer_id'].head(10))

0    OFF0078
1    OFF0059
2    OFF0088
3    OFF0077
4    OFF0083
5    OFF0089
6    OFF0141
7    OFF0008
8    OFF0034
9    OFF0093
Name: officer_id, dtype: object

In [37]:
print(df.columns.tolist())

['incident_id', 'crime_type', 'district', 'city', 'state', 'address', 'latitude', 'longitude', 'officer_id', 'officer_first_name', 'officer_last_name', 'badge_number', 'suspect_id', 'suspect_first_name', 'suspect_last_name', 'suspect_age', 'victim_id', 'victim_first_name', 'victim_last_name', 'victim_age', 'severity', 'resolution', 'num_arrests', 'property_loss_usd', 'reported_online', 'hour', 'day_of_week', 'weapon_used_Blunt Object', 'weapon_used_Firearm', 'weapon_used_Gun', 'weapon_used_Hands/Feet', 'weapon_used_KNIFE', 'weapon_used_Knife', 'weapon_used_Pistol', 'weapon_used_Rifle', 'weapon_used_Unarmed', 'weapon_used_Unknown', 'weapon_used_blunt object', 'weapon_used_firearm', 'weapon_used_hands', 'case_status_Closed', 'case_status_Investgation', 'case_status_OPEN', 'case_status_Open', 'case_status_Pending', 'case_status_Pendng', 'case_status_Resolved', 'case_status_Under Investigation', 'case_status_Unknown', 'case_status_closed', 'case_status_open', 'case_status_under investigation']

In [44]:
# 1. Ensure the columns exist
if 'weapon_used' in df.columns and 'case_status' in df.columns:

    # 2. Clean the text (standardize to lowercase)
    df['weapon_used'] = df['weapon_used'].fillna('unknown').astype(str).str.lower()
    df['case_status'] = df['case_status'].fillna('unknown').astype(str).str.lower()

    # 3. Apply the encoding (this turns the text into your 'bool' columns)
    df = pd.get_dummies(df, columns=['weapon_used', 'case_status'], drop_first=True)

    print("Success: Columns processed and encoded.")
else:
    print("Columns not found. They might have been dropped or renamed earlier.")

Columns not found. They might have been dropped or renamed earlier.

In [45]:
print(df.isnull().sum())

incident_id                           0
crime_type                            0
district                              0
city                                  0
state                                 0
address                               0
latitude                            258
longitude                           289
incident_datetime                   340
officer_id                            0
officer_first_name                    0
officer_last_name                     0
badge_number                        312
suspect_id                          810
suspect_first_name                  810
suspect_last_name                   810
suspect_age                        1097
suspect_gender                     1413
suspect_race                       1601
victim_id                           257
victim_first_name                   257
victim_last_name                    257
victim_age                          562
victim_gender                      1000
victim_phone                       1056
severity                            355
resolution                          951
num_arrests                         333
property_loss_usd                   436
reported_online                     504
notes                              1069
weapon_used_blunt object              0
weapon_used_firearm                   0
weapon_used_gun                       0
weapon_used_hands                     0
weapon_used_hands/feet                0
weapon_used_knife                     0
weapon_used_pistol                    0
weapon_used_rifle                     0
weapon_used_unarmed                   0
weapon_used_unknown                   0
case_status_investgation              0
case_status_open                      0
case_status_pending                   0
case_status_pendng                    0
case_status_resolved                  0
case_status_under investigation       0
case_status_unknown                   0
dtype: int64

In [48]:
# A. Drop rows where critical data is missing (dates)
df.dropna(subset=['incident_datetime'], inplace=True)

# B. Fill categorical/text columns with 'Unknown'
cols_to_fill_unknown = [
    'suspect_gender', 'suspect_race', 'victim_gender',
    'severity', 'resolution', 'reported_online'
]
for col in cols_to_fill_unknown:
    df[col] = df[col].fillna('Unknown')

# C. Fill ID/Name columns with 'Missing' or 0
df[['suspect_id', 'victim_id']] = df[['suspect_id', 'victim_id']].fillna(0)
df[['officer_first_name', 'officer_last_name', 'suspect_first_name',
    'suspect_last_name', 'victim_first_name', 'victim_last_name', 'victim_phone', 'notes']] = \
    df[['officer_first_name', 'officer_last_name', 'suspect_first_name',
        'suspect_last_name', 'victim_first_name', 'victim_last_name', 'victim_phone', 'notes']].fillna('Missing')

# D. Fill Numerical columns with the Median (robust to outliers)
num_cols = ['suspect_age', 'victim_age', 'num_arrests', 'property_loss_usd', 'badge_number', 'latitude', 'longitude']
for col in num_cols:
    # Ensure 'property_loss_usd' is numeric before calculating median
    if col == 'property_loss_usd':
        df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col] = df[col].fillna(df[col].median())

# E. Final Verification
print(df.isnull().sum())

incident_id                        0
crime_type                         0
district                           0
city                               0
state                              0
address                            0
latitude                           0
longitude                          0
incident_datetime                  0
officer_id                         0
officer_first_name                 0
officer_last_name                  0
badge_number                       0
suspect_id                         0
suspect_first_name                 0
suspect_last_name                  0
suspect_age                        0
suspect_gender                     0
suspect_race                       0
victim_id                          0
victim_first_name                  0
victim_last_name                   0
victim_age                         0
victim_gender                      0
victim_phone                       0
severity                           0
resolution                         0
num_arrests                        0
property_loss_usd                  0
reported_online                    0
notes                              0
weapon_used_blunt object           0
weapon_used_firearm                0
weapon_used_gun                    0
weapon_used_hands                  0
weapon_used_hands/feet             0
weapon_used_knife                  0
weapon_used_pistol                 0
weapon_used_rifle                  0
weapon_used_unarmed                0
weapon_used_unknown                0
case_status_investgation           0
case_status_open                   0
case_status_pending                0
case_status_pendng                 0
case_status_resolved               0
case_status_under investigation    0
case_status_unknown                0
dtype: int64

In [49]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4910 entries, 0 to 5249
Data columns (total 48 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   incident_id                      4910 non-null   object
 1   crime_type                       4910 non-null   object
 2   district                         4910 non-null   object
 3   city                             4910 non-null   object
 4   state                            4910 non-null   object
 5   address                          4910 non-null   object
 6   latitude                         4910 non-null   float64
 7   longitude                        4910 non-null   float64
 8   incident_datetime                4910 non-null   object
 9   officer_id                       4910 non-null   object
 10  officer_first_name               4910 non-null   object
 11  officer_last_name                4910 non-null   object
 12  badge_number                     4910 non-null   float64
 13  suspect_id                       4910 non-null   object
 14  suspect_first_name               4910 non-null   object
 15  suspect_last_name                4910 non-null   object
 16  suspect_age                      4910 non-null   float64
 17  suspect_gender                   4910 non-null   object
 18  suspect_race                     4910 non-null   object
 19  victim_id                        4910 non-null   object
 20  victim_first_name                4910 non-null   object
 21  victim_last_name                 4910 non-null   object
 22  victim_age                       4910 non-null   float64
 23  victim_gender                    4910 non-null   object
 24  victim_phone                     4910 non-null   object
 25  severity                         4910 non-null   object
 26  resolution                       4910 non-null   object
 27  num_arrests                      4910 non-null   float64
 28  property_loss_usd                4910 non-null   float64
 29  reported_online                  4910 non-null   object
 30  notes                            4910 non-null   object
 31  weapon_used_blunt object         4910 non-null   bool
 32  weapon_used_firearm              4910 non-null   bool
 33  weapon_used_gun                  4910 non-null   bool
 34  weapon_used_hands                4910 non-null   bool
 35  weapon_used_hands/feet           4910 non-null   bool
 36  weapon_used_knife                4910 non-null   bool
 37  weapon_used_pistol               4910 non-null   bool
 38  weapon_used_rifle                4910 non-null   bool
 39  weapon_used_unarmed              4910 non-null   bool
 40  weapon_used_unknown              4910 non-null   bool
 41  case_status_investgation         4910 non-null   bool
 42  case_status_open                 4910 non-null   bool
 43  case_status_pending              4910 non-null   bool
 44  case_status_pendng               4910 non-null   bool
 45  case_status_resolved             4910 non-null   bool
 46  case_status_under investigation  4910 non-null   bool
 47  case_status_unknown              4910 non-null   bool
dtypes: bool(17), float64(7), object(24)
memory usage: 1.3+ MB
None

In [50]:
# List your ID columns
id_cols = ['incident_id', 'officer_id', 'suspect_id', 'victim_id']

# 1. Clean them: Strip whitespace, convert to string, and ensure they are exactly as they should be
for col in id_cols:
    df[col] = df[col].astype(str).str.strip()

# 2. OPTIONAL: If you have mixed types (some numbers, some strings),
# this ensures everything is a consistent string format
df[id_cols] = df[id_cols].fillna('0').astype(str)

# 3. Verify
print(df[id_cols].info())

<class 'pandas.core.frame.DataFrame'>
Index: 4910 entries, 0 to 5249
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   incident_id  4910 non-null   object
 1   officer_id   4910 non-null   object
 2   suspect_id   4910 non-null   object
 3   victim_id    4910 non-null   object
dtypes: object(4)
memory usage: 191.8+ KB
None

In [52]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4910 entries, 0 to 5249
Data columns (total 48 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   incident_id                      4910 non-null   object
 1   crime_type                       4910 non-null   object
 2   district                         4910 non-null   object
 3   city                             4910 non-null   object
 4   state                            4910 non-null   object
 5   address                          4910 non-null   object
 6   latitude                         4910 non-null   float64
 7   longitude                        4910 non-null   float64
 8   incident_datetime                4910 non-null   object
 9   officer_id                       4910 non-null   object
 10  officer_first_name               4910 non-null   object
 11  officer_last_name                4910 non-null   object
 12  badge_number                     4910 non-null   float64
 13  suspect_id                       4910 non-null   object
 14  suspect_first_name               4910 non-null   object
 15  suspect_last_name                4910 non-null   object
 16  suspect_age                      4910 non-null   float64
 17  suspect_gender                   4910 non-null   object
 18  suspect_race                     4910 non-null   object
 19  victim_id                        4910 non-null   object
 20  victim_first_name                4910 non-null   object
 21  victim_last_name                 4910 non-null   object
 22  victim_age                       4910 non-null   float64
 23  victim_gender                    4910 non-null   object
 24  victim_phone                     4910 non-null   object
 25  severity                         4910 non-null   object
 26  resolution                       4910 non-null   object
 27  num_arrests                      4910 non-null   float64
 28  property_loss_usd                4910 non-null   float64
 29  reported_online                  4910 non-null   object
 30  notes                            4910 non-null   object
 31  weapon_used_blunt object         4910 non-null   bool
 32  weapon_used_firearm              4910 non-null   bool
 33  weapon_used_gun                  4910 non-null   bool
 34  weapon_used_hands                4910 non-null   bool
 35  weapon_used_hands/feet           4910 non-null   bool
 36  weapon_used_knife                4910 non-null   bool
 37  weapon_used_pistol               4910 non-null   bool
 38  weapon_used_rifle                4910 non-null   bool
 39  weapon_used_unarmed              4910 non-null   bool
 40  weapon_used_unknown              4910 non-null   bool
 41  case_status_investgation         4910 non-null   bool
 42  case_status_open                 4910 non-null   bool
 43  case_status_pending              4910 non-null   bool
 44  case_status_pendng               4910 non-null   bool
 45  case_status_resolved             4910 non-null   bool
 46  case_status_under investigation  4910 non-null   bool
 47  case_status_unknown              4910 non-null   bool
dtypes: bool(17), float64(7), object(24)
memory usage: 1.3+ MB
None

In [53]:
# Save the cleaned DataFrame to a CSV file
df.to_csv('final_cleaned_crime_data.csv', index=False)

print("File saved successfully!")

File saved successfully!